services:
  - type: web
    name: meri-gift-card-api
    env: docker
    plan: free
    healthCheckPath: /api/health
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
